import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Loader2, Plus, Trash2, Eye, EyeOff, Wand2, Save, Key } from "lucide-react";

interface EnvVar {
  key: string;
  value: string;
  isSecret: boolean;
  isAutoGenerated: boolean;
}

interface EnvVarsPanelProps {
  projectId: string;
}

export function EnvVarsPanel({ projectId }: EnvVarsPanelProps) {
  const { toast } = useToast();
  const [showSecrets, setShowSecrets] = useState<Record<string, boolean>>({});
  const [newKey, setNewKey] = useState("");
  const [newValue, setNewValue] = useState("");
  const [newIsSecret, setNewIsSecret] = useState(false);

  const { data: envVars = {}, isLoading } = useQuery<Record<string, EnvVar>>({
    queryKey: [`/api/projects/${projectId}/env`],
  });

  const updateMutation = useMutation({
    mutationFn: async (newVars: Record<string, EnvVar>) => {
      await apiRequest("POST", `/api/projects/${projectId}/env`, newVars);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/projects/${projectId}/env`] });
      toast({ title: "Environment variables updated" });
    },
    onError: () => {
      toast({ title: "Failed to update environment variables", variant: "destructive" });
    },
  });

  const autoFixMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", `/api/projects/${projectId}/env/autofix`);
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/projects/${projectId}/env`] });
      toast({ title: "Environment variables auto-generated" });
    },
    onError: () => {
      toast({ title: "Failed to auto-fix environment variables", variant: "destructive" });
    },
  });

  const handleAdd = () => {
    if (!newKey) return;
    const updated = {
      ...envVars,
      [newKey]: {
        key: newKey,
        value: newValue,
        isSecret: newIsSecret,
        isAutoGenerated: false,
      },
    };
    updateMutation.mutate(updated);
    setNewKey("");
    setNewValue("");
    setNewIsSecret(false);
  };

  const handleDelete = (key: string) => {
    const updated = { ...envVars };
    delete updated[key];
    updateMutation.mutate(updated);
  };

  const toggleSecret = (key: string) => {
    setShowSecrets((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const envList = Object.values(envVars);

  return (
    <Card className="border-none shadow-md bg-white dark:bg-slate-900">
      <CardHeader className="flex flex-row items-center justify-between border-b pb-4">
        <div className="space-y-1">
          <CardTitle className="text-lg font-semibold flex items-center gap-2">
            <Key className="h-5 w-5 text-primary" />
            Environment Variables
          </CardTitle>
          <CardDescription>
            Manage environment variables and secrets for your deployment.
          </CardDescription>
        </div>
        <Button
          variant="outline"
          onClick={() => autoFixMutation.mutate()}
          disabled={autoFixMutation.isPending}
          className="border-purple-200 hover:bg-purple-50 text-purple-700 dark:border-purple-800 dark:text-purple-300"
        >
          {autoFixMutation.isPending ? (
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Wand2 className="h-4 w-4 mr-2" />
          )}
          Fix automatically with AI
        </Button>
      </CardHeader>
      <CardContent className="pt-6">
        {isLoading ? (
          <div className="flex justify-center py-8">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
          </div>
        ) : (
          <div className="space-y-6">
            {/* Add New Variable Form */}
            <div className="flex gap-3 items-end bg-slate-50 dark:bg-slate-950 p-4 rounded-lg border">
              <div className="flex-1 space-y-2">
                <label className="text-xs font-medium text-muted-foreground">Key</label>
                <Input
                  placeholder="e.g. API_KEY"
                  value={newKey}
                  onChange={(e) => setNewKey(e.target.value.toUpperCase())}
                  className="font-mono"
                />
              </div>
              <div className="flex-[2] space-y-2">
                <label className="text-xs font-medium text-muted-foreground">Value</label>
                <Input
                  placeholder="Value..."
                  type={newIsSecret ? "password" : "text"}
                  value={newValue}
                  onChange={(e) => setNewValue(e.target.value)}
                  className="font-mono"
                />
              </div>
              <div className="flex items-center h-10 pb-1">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setNewIsSecret(!newIsSecret)}
                  className={newIsSecret ? "text-orange-500" : "text-slate-400"}
                  title="Toggle Secret"
                >
                  {newIsSecret ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </Button>
              </div>
              <Button onClick={handleAdd} disabled={!newKey}>
                <Plus className="h-4 w-4 mr-2" />
                Add
              </Button>
            </div>

            {/* Variables Table */}
            <div className="border rounded-lg overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-[30%]">Key</TableHead>
                    <TableHead className="w-[50%]">Value</TableHead>
                    <TableHead className="w-[10%]">Type</TableHead>
                    <TableHead className="w-[10%] text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {envList.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center py-8 text-muted-foreground">
                        No environment variables configured.
                      </TableCell>
                    </TableRow>
                  ) : (
                    envList.map((env) => (
                      <TableRow key={env.key}>
                        <TableCell className="font-mono font-medium">{env.key}</TableCell>
                        <TableCell className="font-mono text-sm">
                          <div className="flex items-center gap-2">
                            <span className="truncate max-w-[300px]">
                              {env.isSecret && !showSecrets[env.key]
                                ? "••••••••••••••••"
                                : env.value}
                            </span>
                            {env.isSecret && (
                              <button
                                onClick={() => toggleSecret(env.key)}
                                className="text-muted-foreground hover:text-foreground"
                              >
                                {showSecrets[env.key] ? (
                                  <EyeOff className="h-3 w-3" />
                                ) : (
                                  <Eye className="h-3 w-3" />
                                )}
                              </button>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex gap-1">
                            {env.isSecret && (
                              <Badge variant="outline" className="text-orange-500 border-orange-200 bg-orange-50">
                                Secret
                              </Badge>
                            )}
                            {env.isAutoGenerated && (
                              <Badge variant="outline" className="text-purple-500 border-purple-200 bg-purple-50">
                                AI
                              </Badge>
                            )}
                          </div>
                        </TableCell>
                        <TableCell className="text-right">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleDelete(env.key)}
                            className="text-red-500 hover:text-red-700 hover:bg-red-50"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
