import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Loader2, Plus, Trash2, Eye, EyeOff, Wand2, Save, Key, Edit2, X, Lock, Unlock } from "lucide-react";
import { ToastAction } from "@/components/ui/toast";

interface EnvVar {
  key: string;
  value: string;
  isSecret: boolean;
  isAutoGenerated: boolean;
}

interface EnvVarsPanelProps {
  projectId: string;
  onDeploy?: () => void;
  isDeploying?: boolean;
}

export function EnvVarsPanel({ projectId, onDeploy, isDeploying }: EnvVarsPanelProps) {
  const { toast } = useToast();
  const [showSecrets, setShowSecrets] = useState<Record<string, boolean>>({});
  const [newKey, setNewKey] = useState("");
  const [newValue, setNewValue] = useState("");
  const [newIsSecret, setNewIsSecret] = useState(false);
  const [editingKey, setEditingKey] = useState<string | null>(null);

  const { data: envVars = {}, isLoading } = useQuery<Record<string, EnvVar>>({
    queryKey: [`/api/projects/${projectId}/env`],
  });

  const updateMutation = useMutation({
    mutationFn: async (newVars: Record<string, EnvVar>) => {
      const res = await apiRequest("POST", `/api/projects/${projectId}/env`, newVars);
      return res.json();
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: [`/api/projects/${projectId}/env`] });
      if (data.warning) {
        toast({ 
          title: "Saved locally but sync failed", 
          description: data.warning,
          variant: "destructive" 
        });
      } else {
        toast({ 
          title: "Environment variables updated & synced",
          description: onDeploy ? "Changes are live on cloud providers. You may want to redeploy." : "Changes are live on cloud providers.",
          action: onDeploy ? (
            <ToastAction altText="Redeploy" onClick={onDeploy} disabled={isDeploying}>
              {isDeploying ? "Deploying..." : "Redeploy"}
            </ToastAction>
          ) : undefined,
        });
      }
      // Reset form
      setNewKey("");
      setNewValue("");
      setNewIsSecret(false);
      setEditingKey(null);
    },
    onError: () => {
      toast({ title: "Failed to update environment variables", variant: "destructive" });
    },
  });

  const autoFixMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", `/api/projects/${projectId}/env/autofix`);
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/projects/${projectId}/env`] });
      toast({ title: "Environment variables auto-generated" });
    },
    onError: () => {
      toast({ title: "Failed to auto-fix environment variables", variant: "destructive" });
    },
  });

  const handleSave = () => {
    if (!newKey) return;
    const updated = {
      ...envVars,
      [newKey]: {
        key: newKey,
        value: newValue,
        isSecret: newIsSecret,
        isAutoGenerated: false,
      },
    };
    updateMutation.mutate(updated);
  };

  const handleEdit = (env: EnvVar) => {
    setEditingKey(env.key);
    setNewKey(env.key);
    setNewValue(env.value);
    setNewIsSecret(env.isSecret);
    // Scroll to top
    const formElement = document.getElementById("env-form");
    if (formElement) formElement.scrollIntoView({ behavior: "smooth" });
  };

  const handleCancelEdit = () => {
    setEditingKey(null);
    setNewKey("");
    setNewValue("");
    setNewIsSecret(false);
  };

  const handleDelete = (key: string) => {
    const updated = { ...envVars };
    delete updated[key];
    updateMutation.mutate(updated);
  };

  const toggleSecret = (key: string) => {
    setShowSecrets((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const envList = Object.values(envVars);

  return (
    <Card className="border-none shadow-md bg-gradient-to-br from-card to-muted/30 overflow-hidden">
      <CardHeader className="flex flex-row items-center justify-between border-b bg-muted/20 pb-4">
        <div className="space-y-1">
          <CardTitle className="text-lg font-semibold flex items-center gap-2">
            <div className="p-2 rounded-lg bg-primary/10 text-primary">
              <Key className="h-5 w-5" />
            </div>
            Environment Variables
          </CardTitle>
          <CardDescription>
            Manage environment variables and secrets for your deployment.
          </CardDescription>
        </div>
        <Button
          variant="outline"
          onClick={() => autoFixMutation.mutate()}
          disabled={autoFixMutation.isPending}
          className="border-purple-200 hover:bg-purple-50 text-purple-700 dark:border-purple-800 dark:text-purple-300 shadow-sm"
        >
          {autoFixMutation.isPending ? (
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Wand2 className="h-4 w-4 mr-2" />
          )}
          Auto-Detect
        </Button>
      </CardHeader>
      <CardContent className="pt-6">
        {isLoading ? (
          <div className="flex justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-primary/50" />
          </div>
        ) : (
          <div className="space-y-6">
            {/* Add/Edit Variable Form */}
            <div 
              id="env-form" 
              className={`flex flex-col md:flex-row gap-4 items-end p-5 rounded-xl border transition-all duration-300 shadow-sm ${
                editingKey ? "bg-blue-50/50 border-blue-200 dark:bg-blue-900/10 dark:border-blue-800" : "bg-muted/30 border-transparent hover:border-muted"
              }`}
            >
              <div className="flex-1 space-y-2 w-full">
                <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
                  {editingKey ? "Editing Key" : "New Key"}
                </label>
                <div className="relative">
                  <Input
                    placeholder="e.g. DATABASE_URL"
                    value={newKey}
                    onChange={(e) => setNewKey(e.target.value.toUpperCase())}
                    className="font-mono bg-background/50"
                    disabled={!!editingKey} 
                  />
                </div>
              </div>
              <div className="flex-[2] space-y-2 w-full">
                <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Value</label>
                <div className="relative">
                  <Input
                    placeholder="Value..."
                    type={newIsSecret ? "password" : "text"}
                    value={newValue}
                    onChange={(e) => setNewValue(e.target.value)}
                    className="font-mono bg-background/50 pr-10"
                  />
                  <button
                    onClick={() => setNewIsSecret(!newIsSecret)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
                    title={newIsSecret ? "Mark as Public" : "Mark as Secret"}
                  >
                    {newIsSecret ? <Lock className="h-4 w-4" /> : <Unlock className="h-4 w-4" />}
                  </button>
                </div>
              </div>
              
              <div className="flex gap-2 w-full md:w-auto">
                <Button 
                  onClick={handleSave} 
                  disabled={!newKey || updateMutation.isPending}
                  className="flex-1 md:flex-none"
                >
                  {updateMutation.isPending ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : editingKey ? (
                    <>
                      <Save className="h-4 w-4 mr-2" />
                      Update
                    </>
                  ) : (
                    <>
                      <Plus className="h-4 w-4 mr-2" />
                      Add
                    </>
                  )}
                </Button>
                {editingKey && (
                  <Button variant="ghost" onClick={handleCancelEdit} size="icon" className="shrink-0">
                    <X className="h-4 w-4" />
                  </Button>
                )}
              </div>
            </div>

            {/* Variables Table */}
            <div className="border rounded-xl overflow-hidden shadow-sm bg-card">
              <Table>
                <TableHeader>
                  <TableRow className="bg-muted/30 hover:bg-muted/30">
                    <TableHead className="w-[30%] font-semibold">Key</TableHead>
                    <TableHead className="w-[45%] font-semibold">Value</TableHead>
                    <TableHead className="w-[10%] font-semibold">Type</TableHead>
                    <TableHead className="w-[15%] text-right font-semibold">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {envList.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center py-12 text-muted-foreground">
                        <div className="flex flex-col items-center gap-2">
                          <div className="p-3 rounded-full bg-muted">
                            <Key className="h-6 w-6 text-muted-foreground/50" />
                          </div>
                          <p>No environment variables configured.</p>
                          <Button 
                            variant="link" 
                            onClick={() => autoFixMutation.mutate()}
                            className="text-primary"
                          >
                            Auto-detect from code
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ) : (
                    envList.map((env) => (
                      <TableRow key={env.key} className="group transition-colors">
                        <TableCell className="font-mono font-medium text-sm">{env.key}</TableCell>
                        <TableCell className="font-mono text-sm">
                          <div className="flex items-center gap-2">
                            <span className="truncate max-w-[250px] block">
                              {env.isSecret && !showSecrets[env.key]
                                ? ""
                                : env.value}
                            </span>
                            {env.isSecret && (
                              <button
                                onClick={() => toggleSecret(env.key)}
                                className="text-muted-foreground hover:text-primary transition-colors opacity-0 group-hover:opacity-100"
                              >
                                {showSecrets[env.key] ? (
                                  <EyeOff className="h-3.5 w-3.5" />
                                ) : (
                                  <Eye className="h-3.5 w-3.5" />
                                )}
                              </button>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex gap-1 flex-wrap">
                            {env.isSecret && (
                              <Badge variant="outline" className="text-orange-600 border-orange-200 bg-orange-50 dark:bg-orange-900/20 dark:border-orange-800 dark:text-orange-300 text-[10px] px-1.5 py-0 h-5">
                                Secret
                              </Badge>
                            )}
                            {env.isAutoGenerated && (
                              <Badge variant="outline" className="text-purple-600 border-purple-200 bg-purple-50 dark:bg-purple-900/20 dark:border-purple-800 dark:text-purple-300 text-[10px] px-1.5 py-0 h-5">
                                AI
                              </Badge>
                            )}
                          </div>
                        </TableCell>
                        <TableCell className="text-right">
                          <div className="flex justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleEdit(env)}
                              className="h-8 w-8 text-blue-500 hover:text-blue-700 hover:bg-blue-50 dark:hover:bg-blue-900/20"
                            >
                              <Edit2 className="h-3.5 w-3.5" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleDelete(env.key)}
                              className="h-8 w-8 text-red-500 hover:text-red-700 hover:bg-red-50 dark:hover:bg-red-900/20"
                            >
                              <Trash2 className="h-3.5 w-3.5" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
