import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Loader2, Plus, Trash2, Save, Eye, EyeOff, Wand2, Lock, AlertCircle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";

interface EnvVar {
  key: string;
  value: string;
  isSecret: boolean;
  isAutoGenerated: boolean;
  description?: string;
}

interface EnvVarsManagerProps {
  projectId: string;
}

export function EnvVarsManager({ projectId }: EnvVarsManagerProps) {
  const { toast } = useToast();
  const [newKey, setNewKey] = useState("");
  const [newValue, setNewValue] = useState("");
  const [visibleValues, setVisibleValues] = useState<Record<string, boolean>>({});
  const [editingVars, setEditingVars] = useState<Record<string, string>>({}); // key -> value

  const { data: envVars, isLoading } = useQuery<Record<string, EnvVar>>({
    queryKey: [`/api/projects/${projectId}/env`],
  });

  const updateMutation = useMutation({
    mutationFn: async (newVars: Record<string, EnvVar>) => {
      await apiRequest("POST", `/api/projects/${projectId}/env`, newVars);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/projects/${projectId}/env`] });
      toast({ title: "Environment variables saved" });
      setEditingVars({});
    },
    onError: (error: Error) => {
      toast({ 
        title: "Failed to save", 
        description: error.message, 
        variant: "destructive" 
      });
    },
  });

  const autoFixMutation = useMutation({
    mutationFn: async () => {
      await apiRequest("POST", `/api/projects/${projectId}/env/autofix`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/projects/${projectId}/env`] });
      toast({ 
        title: "Auto-detected & Fixed", 
        description: "Missing variables have been added with generated values." 
      });
    },
    onError: (error: Error) => {
      toast({ 
        title: "Auto-fix failed", 
        description: error.message, 
        variant: "destructive" 
      });
    },
  });

  const handleAdd = () => {
    if (!newKey.trim()) return;
    
    const currentVars = envVars || {};
    if (currentVars[newKey]) {
      toast({ title: "Key already exists", variant: "destructive" });
      return;
    }

    const updatedVars = {
      ...currentVars,
      [newKey]: {
        key: newKey,
        value: newValue,
        isSecret: isSecretKey(newKey),
        isAutoGenerated: false
      }
    };

    updateMutation.mutate(updatedVars);
    setNewKey("");
    setNewValue("");
  };

  const handleDelete = (key: string) => {
    const currentVars = envVars || {};
    const { [key]: _, ...rest } = currentVars;
    updateMutation.mutate(rest);
  };

  const handleValueChange = (key: string, value: string) => {
    setEditingVars(prev => ({ ...prev, [key]: value }));
  };

  const handleSaveRow = (key: string) => {
    const currentVars = envVars || {};
    const updatedVars = {
      ...currentVars,
      [key]: {
        ...currentVars[key],
        value: editingVars[key]
      }
    };
    updateMutation.mutate(updatedVars);
  };

  const toggleVisibility = (key: string) => {
    setVisibleValues(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const isSecretKey = (key: string) => {
    const lower = key.toLowerCase();
    return lower.includes("secret") || lower.includes("key") || lower.includes("token") || lower.includes("password");
  };

  if (isLoading) {
    return <div className="flex justify-center p-8"><Loader2 className="h-8 w-8 animate-spin text-muted-foreground" /></div>;
  }

  const varsList = Object.values(envVars || {});

  return (
    <Card className="border-muted/60 shadow-sm">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg flex items-center gap-2">
              <Lock className="h-5 w-5 text-primary" />
              Environment Variables
            </CardTitle>
            <CardDescription>
              Manage secrets and configuration for your deployment.
            </CardDescription>
          </div>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={() => autoFixMutation.mutate()}
            disabled={autoFixMutation.isPending}
            className="gap-2"
          >
            {autoFixMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Wand2 className="h-4 w-4" />}
            Auto-Detect & Fix
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <Alert className="mb-6 bg-blue-50/50 border-blue-100 dark:bg-blue-900/10 dark:border-blue-900/50">
          <AlertCircle className="h-4 w-4 text-blue-600 dark:text-blue-400" />
          <AlertDescription className="text-blue-700 dark:text-blue-300 text-xs">
            These variables will be automatically synced to your deployment provider (Vercel, Render, etc.) when you deploy.
          </AlertDescription>
        </Alert>

        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[30%]">Key</TableHead>
                <TableHead className="w-[50%]">Value</TableHead>
                <TableHead className="w-[20%] text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {varsList.length === 0 && (
                <TableRow>
                  <TableCell colSpan={3} className="text-center py-8 text-muted-foreground">
                    No environment variables defined.
                  </TableCell>
                </TableRow>
              )}
              {varsList.map((envVar) => (
                <TableRow key={envVar.key}>
                  <TableCell className="font-mono text-sm font-medium">
                    {envVar.key}
                    {envVar.isAutoGenerated && (
                      <Badge variant="secondary" className="ml-2 text-[10px] h-4 px-1">Auto</Badge>
                    )}
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <Input 
                        type={visibleValues[envVar.key] ? "text" : "password"}
                        value={editingVars[envVar.key] !== undefined ? editingVars[envVar.key] : envVar.value}
                        onChange={(e) => handleValueChange(envVar.key, e.target.value)}
                        className="font-mono text-xs h-8"
                      />
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 shrink-0"
                        onClick={() => toggleVisibility(envVar.key)}
                      >
                        {visibleValues[envVar.key] ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                      </Button>
                    </div>
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      {editingVars[envVar.key] !== undefined && editingVars[envVar.key] !== envVar.value && (
                        <Button 
                          size="icon" 
                          variant="ghost" 
                          className="h-8 w-8 text-green-600 hover:text-green-700 hover:bg-green-50"
                          onClick={() => handleSaveRow(envVar.key)}
                        >
                          <Save className="h-4 w-4" />
                        </Button>
                      )}
                      <Button 
                        size="icon" 
                        variant="ghost" 
                        className="h-8 w-8 text-muted-foreground hover:text-destructive"
                        onClick={() => handleDelete(envVar.key)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              
              {/* Add New Row */}
              <TableRow className="bg-muted/30">
                <TableCell>
                  <Input 
                    placeholder="NEW_KEY" 
                    value={newKey}
                    onChange={(e) => setNewKey(e.target.value.toUpperCase())}
                    className="font-mono text-xs h-8"
                  />
                </TableCell>
                <TableCell>
                  <Input 
                    placeholder="Value" 
                    value={newValue}
                    onChange={(e) => setNewValue(e.target.value)}
                    className="font-mono text-xs h-8"
                  />
                </TableCell>
                <TableCell className="text-right">
                  <Button 
                    size="sm" 
                    onClick={handleAdd}
                    disabled={!newKey.trim() || updateMutation.isPending}
                    className="h-8"
                  >
                    <Plus className="h-4 w-4 mr-1" /> Add
                  </Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </CardContent>
    </Card>
  );
}
